FROM node:18-alpine

WORKDIR /app

# Installation des dépendances
COPY package*.json ./
RUN npm install

# Port Vite
EXPOSE 5173

# Commande de développement avec hot-reload
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
